# Generated by Django 4.2.7 on 2023-11-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_address_zip_code_address_zip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
    ]
