# Generated by Django 4.2.7 on 2023-11-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_address_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
